module.exports = {
  ...require('./checkDescendent'),
  ...require('./checkElement'),
  ...require('./clickDescendent'),
  ...require('./clickElement'),
  ...require('./fileUpload'),
  ...require('./setSelectOption'),
  ...require('./setText'),
  ...require('./typeText'),
  ...require('./pressKey'),
  ...require('./wait'),
  ...require('./waitForPageLoad'),
  ...require('./waitForSelectorState'),
  ...require('./waitForUrl'),
  ...require('./mouseLeavePage'),
}
